export const PROFILE_KNOWLEDGE_DOCS = [
  "I am Asad Ullah, a mobile app developer based in Model Town, Lahore, Pakistan.",
  "I have 3+ years of mobile development experience and have worked at RootPointers, BritSols, Ride Options, and MicroProgramers.",
  "My core stack includes Flutter, Dart, iOS with Swift and SwiftUI, and React Native.",
  "I build cross-platform apps, backend integrations, clean architecture systems, and CI/CD release pipelines.",
  "At RootPointers (Jan 2025 to present), I worked on enterprise OTA update systems, automated CI/CD, and real-time communication modules with Firebase and REST APIs.",
  "At BritSols (Jun 2024 to Dec 2024), I delivered production Flutter apps with custom Node.js backends and performance optimization.",
  "At Ride Options (Aug 2023 to May 2024), I built ride-sharing modules with real-time GPS, chat, booking flows, and codebase stability improvements.",
  "At MicroProgramers, I contributed from internship to junior role, built reusable UI components, and improved testing practices.",
  "I have worked in healthcare, e-commerce, ride-sharing, and enterprise projects.",
  "I follow clean architecture, modular code patterns, and strong Git workflows.",
  "I have published an open source Flutter plugin named easypaisa_flutter for Easypaisa payment integration in Pakistan.",
  "The easypaisa_flutter package is available on GitHub and pub.dev and exposes a cleaner Dart API for Easypaisa mobile account flows.",
  "I am open to full-time roles, freelance projects, and collaboration opportunities.",
  "Primary contact email is asadbalqani@gmail.com.",
  "LinkedIn profile is linkedin.com/in/theasadsahir.",
  "GitHub profile is github.com/Asad06124.",
  "Phone number is +92 317 6854356.",
  "Education includes BS Computer Science from GCUF in 2023.",
  "Technical strengths include Flutter state management (GetX, Riverpod, BLoC, Provider), Firebase, REST APIs, CI/CD, and release workflows.",
  "I care about shipping reliable, performant apps with clear user experience and maintainable codebases."
];
